enlace/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('linkapp.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

linkapp/urls.py
from django.urls import path
from . import views

app_name = 'linkapp'
urlpatterns = [
    path('',views.home, name='home'),
    path('agregar/', views.agregar, name='agregar'),
    path('editar/<str:pk>', views.editar, name='editar'),
    path('eliminar/<str:pk>', views.eliminar, name='eliminar'),
    

]

linkapp/models.py
from django.db import models

class Enlace(models.Model):
    titulo = models.CharField(max_length=250)
    descripcion = models.CharField(max_length=250)
    enlace = models.CharField(max_length=250)

    def __str__(self):
        return self.titulo

linkapp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Enlace

class EnlaceForm(forms.ModelForm):
    class Meta:
        model = Enlace
        fields = '__all__'
        labels = {
            'titulo':'Titulo',
            'descripcion':'Descripcion',
            'enlace':'Enlace'
        }
       

     

linkapp/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .forms import EnlaceForm
from .models import Enlace



def home(request):
    enlaces = Enlace.objects.all()
    return render(request, 'linkapp/home.html', {'enlaces':enlaces})
    
    
    

def agregar(request):
    if request.method=='POST':
        form = EnlaceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = EnlaceForm()        
    return render(request, 'linkapp/agregar.html', {'form':form})

def editar(request, pk):
    enlace = Enlace.objects.get(id=pk)
    form = EnlaceForm(instance=enlace)
    if request.method=='GET':
       form = EnlaceForm(instance=enlace)
    else:   
        form = EnlaceForm(request.POST, instance=enlace)
        if form.is_valid():
           form.save()
           return redirect('/')
        

    return render(request, 'linkapp/editar.html', {'form':form})

def eliminar(request, pk):
    enlace = Enlace.objects.get(id=pk)
    enlace.delete()
    return redirect('/')



        

linkapp/templates/linkapp/agregar.html
{% extends 'linkapp/plantilla.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container" style="text-align: center;">
    <h1>Agregar Enlace</h1>
    <form action="" method="POST">{% csrf_token %}
    <div class="form-control">
        <p>{{form.titulo.label}}</p>
        {% render_field form.titulo class+="form-control" %}
    </div>
    <div class="form-control">
        <p>{{form.descripcion.label}}</p>
        {% render_field form.descripcion class+="form-control" %}
    </div>
    <div class="form-control">
        <p>{{form.enlace.label}}</p>
        {% render_field form.enlace class+="form-control" %}
    </div>
    <div class="action">
        <button type="submit" class="btn btn-success" style="width: 100%;">Agregar</button>
    </div>
    </form>
</div>
{% endblock %}

linkapp/templates/linkapp/editar.html
{% extends 'linkapp/plantilla.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container" style="text-align: center;">
    <h1>Actualizar Enlace</h1>
    <form action="" method="POST">{% csrf_token %}
    <div class="form-control">
        <p>{{form.titulo.label}}</p>
        {% render_field form.titulo class+="form-control" %}
    </div>
    <div class="form-control">
        <p>{{form.descripcion.label}}</p>
        {% render_field form.descripcion class+="form-control" %}
    </div>
    <div class="form-control">
        <p>{{form.enlace.label}}</p>
        {% render_field form.enlace class+="form-control" %}
    </div>
    <div class="action">
        <button type="submit" class="btn btn-success" style="width: 100%;">Actualizar</button>
    </div>
    </form>
</div>
{% endblock %}

linkapp/templates/linkapp/home.html
{% extends 'linkapp/plantilla.html' %}
{% block content %}
<div class="container" style="text-align: center;">
    <h1>Enlances de Interes</h1>
    <a href="{% url 'linkapp:agregar' %}" class="btn btn-primary btn-block active" role="button" aria-pressed="true">AGREGAR NUEVO ENLACE</a>
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col-3">Titulo</th>
            <th scope="col-4">Descripcion</th>
            <th scope="col-1">Enlace</th>
            <th scope="col-2">Editar</th>
            <th scope="col-2">borrar</th>
          </tr>
        </thead>
        <tbody>
            {% for enlace in enlaces %}
          <tr>
            <td>{{enlace.titulo}}</td>
            <td>{{enlace.descripcion}}</td>
            <td><a href="{{enlace.enlace}}" class="btn btn-success btn-lg active" role="button" aria-pressed="true"><i class="fa fa-link"></i></a></td>
            <td><a href="{% url 'linkapp:editar' enlace.id %}" class="btn btn-info btn-lg active" role="button" aria-pressed="true"><i class="fas fa-pen"></i></a></i></td>
            <td><a href="{% url 'linkapp:eliminar' enlace.id %}" class="btn btn-warning btn-lg active" role="button" aria-pressed="true"><i class="fas fa-trash"></i></a></td>
           
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
</div>
{% endblock %}

linkapp/templates/linkapp/plantilla.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    
</head>
<body>
    {% block content %}
    {% endblock %}
 
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> 
</body>
</html>